print("Welcome to quize game!")
play = input("DO you want to play this game? ")
print(play)
if play!="yes":
    quit()

print("OK! let's play .")
print("QUESTION 1")
answer=input("What does CPU stands for? ")
print("CORRECT" if answer=="cental processing unit" else "INCORRECT")
print("QUESTION 2")
answer=input("What does GPU stands for? ")
print("CORRECT" if answer=="graphics processing unit" else "INCORRECT")
print("QUESTION 3")
answer=input("What does RAM stands for? ")
print("CORRECT" if answer=="random acess memory" else "INCORRECT")
print("QUESTION 4")
answer=input("What does CPU stands for? ")
print("CORRECT" if answer=="cental processing unit" else "INCORRECT")
